---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: upgrad-cluster 
  region: ap-south-1
  version: "1.24" 
vpc: 
  id: "vpc-0c05e98e7406d3ae5"
  subnets:
    public:
      public-subnet-1a:
        id: "subnet-0789146a0f9f361f5"
        az: "ap-south-1a"
      public-subnet-1b:
        id: "subnet-0da4cced2aaa95005"
        az: "ap-south-1b"
    private:
      private-subnet-1a:
        id: "subnet-0d801e88cf460f957"
        az: "ap-south-1a"
      private-subnet-1b:
        id: "subnet-05986c328510251fe"
        az: "ap-south-1b"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  nat:
    gateway: Disable 

iam: 
  withOIDC: true
  serviceAccounts: 
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true

nodeGroups: 
  - name: private-1a
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true" 
      k8s.io/cluster-autoscaler/saurav-capstone-cluster: "shared" 
    instancesDistribution:
      instanceTypes:
        - t3a.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    privateNetworking: true 
    subnets:
      - private-subnet-1a 
  - name: public-1a
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/saurav-capstone-project: "shared"
    instancesDistribution:
      instanceTypes:
        - t3a.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    subnets:
      - public-subnet-1a