apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ca-cluster 
  region: ap-south-1
  version: "1.24" 
vpc: 
  id: "vpc-0c05e98e7406d3ae5"
  subnets:
    public:
      public-subnet-1a:
        id: "subnet-0789146a0f9f361f5"
        az: "ap-south-1a"
      public-subnet-1b:
        id: "subnet-0da4cced2aaa95005"
        az: "ap-south-1b"
    private:
      private-subnet-1a:
        id: "subnet-0d801e88cf460f957"
        az: "ap-south-1a"
      private-subnet-1b:
        id: "subnet-05986c328510251fe"
        az: "ap-south-1b"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  metadata:
  name: basic-cluster
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
