apiVersion: apps/v1
kind: Deployment
metadata:
  name: upgrad-app
  labels:
    app: upgrad-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upgrad-app
  template:
    metadata:
      labels:
        app: upgrad-app
    spec:
      containers:
      - name: upgrad-app
        image: public.ecr.aws/y2j8x9n3/upg-app:latest
        ports:
        - containerPort: 8081
      tolerations:
      - key: "special"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"