apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ca-cluster 
  region: ap-south-1

nodeGroups: 
  - name: private-1a
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true" 
      k8s.io/cluster-autoscaler/saurav-capstone-cluster: "shared" 
    instancesDistribution:
      instanceTypes:
        - t3a.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    privateNetworking: true 
    subnets:
      - subnet-0d801e88cf460f957 
    taints:
      - key: special
        value: "true"
        effect: NoSchedule